// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06/05/2026, 12:41:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Nuxt/portfolio-v2/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Nuxt/portfolio-v2/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Nuxt/portfolio-v2/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Nuxt/portfolio-v2/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Nuxt/portfolio-v2/app/plugins/**/*.{js,ts,mjs}","C:/Nuxt/portfolio-v2/app/composables/**/*.{js,ts,mjs}","C:/Nuxt/portfolio-v2/app/utils/**/*.{js,ts,mjs}","C:/Nuxt/portfolio-v2/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Nuxt/portfolio-v2/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Nuxt/portfolio-v2/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Nuxt/portfolio-v2/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;